"""add_survey_offer_fields_to_user

Revision ID: 11f5d0c38139
Revises: d8f84d21158c
Create Date: 2025-10-14 21:53:57.810017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f5d0c38139'
down_revision: Union[str, None] = 'd8f84d21158c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('survey_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('survey_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('survey_skipped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('msgs_since_skip', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('offer_attempt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_offer_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('survey_offer_snooze_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'survey_offer_snooze_until')
    op.drop_column('users', 'last_offer_at')
    op.drop_column('users', 'offer_attempt')
    op.drop_column('users', 'msgs_since_skip')
    op.drop_column('users', 'survey_skipped_at')
    op.drop_column('users', 'survey_completed_at')
    op.drop_column('users', 'survey_completed')
    # ### end Alembic commands ###