"""add_sell_scripts_table

Revision ID: 13068cd26c23
Revises: 74e8a2490a3a
Create Date: 2025-10-14 16:52:34.156468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '13068cd26c23'
down_revision: Union[str, None] = '74e8a2490a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('sell_scripts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sheet', sa.String(length=100), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_hash')
    )
    op.create_index('ix_sell_scripts_updated_at', 'sell_scripts', ['updated_at'], unique=False)
    op.create_table('admin_outbound_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.BigInteger(), nullable=False),
    sa.Column('recipients', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('content_kind', sa.String(length=50), nullable=False),
    sa.Column('text_snippet', sa.String(length=500), nullable=True),
    sa.Column('media_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admins.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_outbound_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('outbound_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=255), nullable=True),
    sa.Column('delivered_message_id', sa.BigInteger(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outbound_id'], ['admin_outbound_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_outbound_results_outbound_id', 'admin_outbound_results', ['outbound_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_outbound_results_outbound_id', table_name='admin_outbound_results')
    op.drop_table('admin_outbound_results')
    op.drop_table('admin_outbound_messages')
    op.drop_index('ix_sell_scripts_updated_at', table_name='sell_scripts')
    op.drop_table('sell_scripts')
    op.execute('DROP EXTENSION IF EXISTS vector')
    # ### end Alembic commands ###