"""add_incomplete_lead_tracking

Revision ID: 39e79cdf9a27
Revises: 11f5d0c38139
Create Date: 2025-10-14 22:23:19.377267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e79cdf9a27'
down_revision: Union[str, None] = '11f5d0c38139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('incomplete_job_id', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('assignee_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'assignee_id')
    op.drop_column('leads', 'incomplete_job_id')
    # ### end Alembic commands ###