"""add_utc_slot_and_attendance_to_appointment

Revision ID: 74e8a2490a3a
Revises: 3eab965596e0
Create Date: 2025-10-14 15:40:56.562097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74e8a2490a3a'
down_revision: Union[str, None] = '3eab965596e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_constraint('fk_ab_results_variant', 'ab_results', type_='foreignkey')
    op.create_foreign_key(None, 'ab_results', 'ab_variants', ['variant_id'], ['id'])
    op.add_column('appointments', sa.Column('slot_utc', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('attendance', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('appointments', sa.Column('source', sa.String(length=50), nullable=True))
    op.drop_index('ix_product_match_log_created', table_name='product_match_log')
    op.drop_index('ix_product_match_log_user', table_name='product_match_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_product_match_log_user', 'product_match_log', ['user_id'], unique=False)
    op.create_index('ix_product_match_log_created', 'product_match_log', ['matched_at'], unique=False)
    op.drop_column('appointments', 'source')
    op.drop_column('appointments', 'attendance')
    op.drop_column('appointments', 'slot_utc')
    op.drop_constraint(None, 'ab_results', type_='foreignkey')
    op.create_foreign_key('fk_ab_results_variant', 'ab_results', 'ab_variants', ['variant_id'], ['id'], ondelete='SET NULL')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###