"""full_ab_testing_cycle

Revision ID: 7caf8c9acbfd
Revises: e7dc54f47227
Create Date: 2025-10-14 18:56:13.470479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7caf8c9acbfd'
down_revision: Union[str, None] = 'e7dc54f47227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_metrics_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('delivered', sa.Integer(), nullable=False),
    sa.Column('clicked', sa.Integer(), nullable=False),
    sa.Column('responded', sa.Integer(), nullable=False),
    sa.Column('converted', sa.Integer(), nullable=False),
    sa.Column('unsubscribed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['ab_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['ab_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'variant_id', 'metric_date', name='uq_ab_metrics_daily_unique')
    )
    op.create_index('ix_ab_metrics_daily_test_date', 'ab_metrics_daily', ['test_id', 'metric_date'], unique=False)
    op.add_column('ab_assignments', sa.Column('first_delivery_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ab_assignments', sa.Column('delivery_status', sa.String(length=10), server_default='PENDING', nullable=False))
    op.add_column('ab_tests', sa.Column('sample_ratio', sa.Numeric(precision=4, scale=3), server_default=sa.text("'0.1'"), nullable=False))
    op.add_column('ab_tests', sa.Column('observation_hours', sa.Integer(), server_default=sa.text("'24'"), nullable=False))
    op.add_column('ab_tests', sa.Column('segment_filter', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('ab_tests', sa.Column('winner_variant_id', sa.BigInteger(), nullable=True))
    op.add_column('ab_tests', sa.Column('delivered_group_id', sa.UUID(), nullable=True))
    op.add_column('ab_tests', sa.Column('send_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ab_tests', sa.Column('created_by_admin_id', sa.BigInteger(), server_default=sa.text("'0'"), nullable=False))
    op.alter_column('ab_tests', 'population',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_ab_tests_send_at', 'ab_tests', ['send_at'], unique=False)
    op.create_index('ix_ab_tests_status', 'ab_tests', ['status'], unique=False)
    op.create_index('ix_ab_tests_winner_variant_id', 'ab_tests', ['winner_variant_id'], unique=False)
    op.create_foreign_key(None, 'ab_tests', 'ab_variants', ['winner_variant_id'], ['id'])
    op.add_column('ab_variants', sa.Column('media', sa.JSON(), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('ab_variants', sa.Column('parse_mode', sa.String(length=10), server_default='HTML', nullable=False))
    op.alter_column('ab_variants', 'buttons',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ab_variants', 'buttons',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('ab_variants', 'parse_mode')
    op.drop_column('ab_variants', 'media')
    op.drop_constraint(None, 'ab_tests', type_='foreignkey')
    op.drop_index('ix_ab_tests_winner_variant_id', table_name='ab_tests')
    op.drop_index('ix_ab_tests_status', table_name='ab_tests')
    op.drop_index('ix_ab_tests_send_at', table_name='ab_tests')
    op.alter_column('ab_tests', 'population',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('ab_tests', 'created_by_admin_id')
    op.drop_column('ab_tests', 'send_at')
    op.drop_column('ab_tests', 'delivered_group_id')
    op.drop_column('ab_tests', 'winner_variant_id')
    op.drop_column('ab_tests', 'segment_filter')
    op.drop_column('ab_tests', 'observation_hours')
    op.drop_column('ab_tests', 'sample_ratio')
    op.drop_column('ab_assignments', 'delivery_status')
    op.drop_column('ab_assignments', 'first_delivery_at')
    op.drop_index('ix_ab_metrics_daily_test_date', table_name='ab_metrics_daily')
    op.drop_table('ab_metrics_daily')
    # ### end Alembic commands ###