"""add_followup_functionality

Revision ID: e7dc54f47227
Revises: 13068cd26c23
Create Date: 2025-10-14 18:41:18.616467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7dc54f47227'
down_revision: Union[str, None] = '13068cd26c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followup_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', name='followup_templates_kind_uq')
    )
    op.add_column('users', sa.Column('last_user_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_followup_24_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_followup_72_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('mute_followups_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('followups_opted_out', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'followups_opted_out')
    op.drop_column('users', 'mute_followups_until')
    op.drop_column('users', 'last_followup_72_sent_at')
    op.drop_column('users', 'last_followup_24_sent_at')
    # ### end Alembic commands ###

    op.execute("""
        INSERT INTO followup_templates (kind, title, text, media)
        VALUES
        ('24h', 'Follow-up 24h', '👋 {first_name}, вы вчера начали диалог, но мы не успели договорить.\nЯ подготовил короткую подсказку по следующим шагам и подарок. Хотите вернусь к вашему вопросу?', '[]'),
        ('72h', 'Follow-up 72h', 'Привет, {first_name}! Напомню о бонусе и быстрой консультации (15–20 минут) — подскажу по шагам, без навязывания. Готовы подобрать удобное время?', '[]')
    """)
    op.drop_column('users', 'last_user_activity_at')
    op.drop_table('followup_templates')
    # ### end Alembic commands ###