"""add ab_assignments table

Revision ID: ea9197f7dfd8
Revises: 7caf8c9acbfd
Create Date: 2025-10-14 20:07:39.569993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9197f7dfd8'
down_revision: Union[str, None] = '7caf8c9acbfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###